[package]
name = "mosaic"
version = "0.1.0"
authors = ["Pepijn de Vos <pepijndevos@gmail.com>"]
edition = "2018"

[dependencies]
vgtk = { path = "../vgtk/vgtk" }
cairo-rs = "0.9.0"
pretty_env_logger = "0.4"
