# SPDX-FileCopyrightText: 2022 Pepijn De Vos <pepijndevos@gmail.com>
# SPDX-FileCopyrightText: 2022 NyanCAD Mosaic
#
# SPDX-License-Identifier: GPL-3.0-only

name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build js
        run: |
          npm install
          npx shadow-cljs release frontend

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: public
          target-folder: app
